### ISSUE TITLE
Runner & prometheus stack alertmanager uses wrong URL when GKE VPC scope DNS is used

### ISSUE THREAD

**Issue by yahya-hrln** [robusta-dev/robusta#1025]
**Describe the bug**
With [GKE VPC scope DNS](https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-dns#vpc_scope_dns), the cluster DNS uses a custom suffix instead of `svc.cluster.local`. 

**To Reproduce**
1. Deploy Robusta on GKE with VPC scope DNS enabled, with Prometheus stack enabled
2. Check alertmanager & runner logs

**Expected behavior**
DNS resolution working properly

**Screenshots**

Alertmanager Logs

```
ts=2023-08-09T08:43:16.945Z caller=notify.go:732 level=warn component=dispatcher receiver=robusta integration=webhook[0] msg="Notify attempt failed, will retry later" attempts=1 err="Post \"http://robusta-runner.monitoring.svc.cluster.local/api/alerts\": dial tcp: lookup robusta-runner.monitoring.svc.cluster.local on 169.254.20.10:53: no such host"
```

**Comment by pavangudiwada** [comment]
Hi @yahya-hrln thank you for raising an issue and creating a PR to fix it. We apologize for the delay. Our team is looking into it.

**Comment by anakaiti** [comment]
Hi @pavangudiwada, any chance we can push this forward?

**Comment by aantn** [comment]
Hi @anakaiti,
Sorry about the delay. Arik left some comments for you on the PR to address before merging.
