### ISSUE TITLE
time_intervals ability like in alertmanager

### ISSUE THREAD

**Issue by lictw** [robusta-dev/robusta#1027]
I want to have a single chat where non-critical alerts sending only in work time, but critical always. I tried to achieve this with settings in alertmanager, but robusta should receive alerts always for history reason, just not sending them.

**Comment by arikalon1** [comment]
Thanks for reporting it @lictw 

We have adding `activity hours` on the sinks, on our roadmap.
Would you be interested in contributing this part?

**Comment by lictw** [comment]
It's nice, I can't contribute big programs with python, so I'm just waiting..) Thanks!
