### ISSUE TITLE
silence creation link from Discord sends bad cluster-name

### ISSUE THREAD

**Issue by kayahk** [robusta-dev/robusta#1039]
**Describe the bug**
When I click on the `silence` button in a Discord alert notification, the pre-selected cluster-name and the list of optional additional cluster-names are broken. 

**To Reproduce**
1. Go to any alert notification in any Discord channel
2. Click on the 'Silence' button linking to the Robusta platform
3. Try to add the silence record for the selected alert notification
4. See error (screenshots)

**Expected behavior**
The silence record should be added to Alertmanager.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS 13.4.1
 - chrome 115.0.5790.170 arm64
 - Robusta version 0.10.21 

**Additional context**
It looks like the previously working feature of clicking the `Silence` link from the Discord alert does not work properly, as the cluster-name is not selected from the list, although the list caption says `1 of 5 clusters`.
<img width="743" alt="Screenshot 2023-08-17 at 16 05 04" src="https://github.com/robusta-dev/robusta/assets/80452889/20f271ed-ef23-4140-93b4-28cce87eb15c">

 If the cluster-name is selected manually, the caption changes to `2 of clusters`, but the list of cluster-names on the top has a leading `,` (comma) which is likely causing the `create` action to fail.
<img width="604" alt="Screenshot 2023-08-17 at 16 05 44" src="https://github.com/robusta-dev/robusta/assets/80452889/148008d3-ea42-4505-b39e-6525af69f7a5">
<img width="387" alt="Screenshot 2023-08-17 at 16 08 04" src="https://github.com/robusta-dev/robusta/assets/80452889/ab863e21-a79c-4dae-9076-11187126fc84">

Creating silences the regular way (not from a Discord alert link) works perfectly fine.

**Comment by kayahk** [comment]
Just found out that the same behaviour described above also appears when trying to duplicate (copy) an existing silence record.

**Comment by arikalon1** [comment]
Thanks for reporting it @kayahk 
We'll look into it

**Comment by arikalon1** [comment]
@kayahk , we applied a fix that was causing it. 
Closing it.
