### ISSUE TITLE
dynamic channel on the teams sink

### ISSUE THREAD

**Issue by gioppoluca** [robusta-dev/robusta#1083]
**Is your feature request related to a problem?**
The need is to choose the teams where to send info dynamically without having to change anything in robusta.
Teams are associated to projects that are managed outside Robusta: the ability to read labels from Alerts (through alert relabeling) will enable Robusta to send to a sink it does not know and is not hard coded in its configurartion

**Describe the solution you'd like**
Solution similar to slack where sink info is red from labels/annotations

**Describe alternatives you've considered**
Defining CR for sink that are placed in the project NS and Robusta able to watch for these CR and configure itself to use those new CR

**Additional context**
Talked about this on Slack with @arikalon1

**Comment by gioppoluca** [comment]
to be more specific the need is to override the existing configuration of the teams configuration:
```
sinksConfig:
- ms_teams_sink:
    name: dynamic_ms_teams_sink
    webhook_url: teams channel incoming webhook  # see video below
```

I believe that at the moment Robusta require that we define a MSTeams like the `dynamic_ms_teams_sink`
The need is to override the `webhook_url` with the value taken from the label/annotation (probably annotations should be better).
In this way we can have an existing sink configuration that robusta needs to wire its stuff but we would dynamically send to different destinations every time.

**Comment by RoiGlinik** [comment]
@gioppoluca This will be available in the next version
