### ISSUE TITLE
SMTP sink basic configuration

### ISSUE THREAD

**Issue by nohant** [robusta-dev/robusta#1094]
**Is your feature request related to a problem?**
I would like to be able to use a simple SMTP sink which will allow me to receive email from various alerts.

**Describe the solution you'd like**
```
sinksConfig:
- smtp:                  # sink type
    name:           # arbitrary name
    host:             # a sink-specific parameter
    user:                      # optional routing rules (see below)
    password:                  # optional (see below)
```

**Describe alternatives you've considered**
at the moment there is no sink to be utilised directly by robusta, as a workaround we are using `alertmanager` for that.

i will Gladly help hopewhever i can.

**Comment by Sheeproid** [comment]
Hey - @RobertSzefler is working on something similar that and will probably come out in the next version of Robusta

**Comment by Sheeproid** [comment]
https://github.com/robusta-dev/robusta/pull/1128
