### ISSUE TITLE
Helm: Possibility to set PodSecurityContext as well as individual container SecurityContext

### ISSUE THREAD

**Issue by tibuntu** [robusta-dev/robusta#1103]
**Is your feature request related to a problem?**
We have very strict policies for our Kubernetes clusters. Especially certain values in the SecurityContext of pods & containers are required so that pods are accepted by the API.

**Describe the solution you'd like**
It would be fantastic, if one could modify the PodSecurityContext as well as the individual container SecurityContext via the Helm-Values.

**Comment by aantn** [comment]
Hi @tibuntu,
We don't have the option yet, but a PR would be welcome as long as it doesn't change the default behaviour. See here - https://github.com/robusta-dev/robusta/blob/master/helm/robusta/templates/runner-service-account.yaml
