### ISSUE TITLE
Add Custom labels on pods

### ISSUE THREAD

**Issue by michMartineau** [robusta-dev/robusta#1131]
**Is your feature request related to a problem?**
We would like to use Robusta in order to generate alerts from k8s ressources.
We will run forwarder pods and runner pods in a kubernetes clusters.
We used to add some custom labels on pods  in order to follow them.

For example :
 - managed-by
 - name
 - owned-by
 - part-of
 - repository

**Describe the solution you'd like**
I would like to have the possibility to add custom labels

**Additional context**
I've proposed the following pull request https://github.com/robusta-dev/robusta/pull/1129

**Comment by aantn** [comment]
@michMartineau this is fixed by https://github.com/robusta-dev/robusta/pull/1129 and we can close, right?

**Comment by michMartineau** [comment]
Hi Natan, thx a lot for the approval. Yes we can close it
