### ISSUE TITLE
Feature Request: Support for Labels and Annotations with Special Characters in Dynamic Routing

### ISSUE THREAD

**Issue by levtomer66** [robusta-dev/robusta#1133]
**Is your feature request related to a problem?**
Currently, the system supports routing labels and annotations for dynamic routing, which is a valuable feature. However, it does not support labels with special characters, such as "app.kubernetes.io/owner: X." This limitation is a problem for users who need to use special characters in their labels.

**Describe the solution you'd like**
I would like the system to support labels and annotations with special characters. Specifically, I want the ability to use labels like "app.kubernetes.io/owner: X" for dynamic routing. This would provide greater flexibility and accuracy in configuring routing rules.

**Describe alternatives you've considered**
As an alternative, users can currently work around this limitation by avoiding special characters in labels and annotations. However, this is not always practical or desirable, as it may result in less descriptive or less organized labels.

**Additional context**
Support for labels with special characters, such as "app.kubernetes.io/owner: X," would greatly enhance the functionality of the dynamic routing system, making it more versatile and accommodating for various use cases.

**Comment by aantn** [comment]
Hey, this sounds like a good improvement. Any interest in opening a PR for this? We would love to guide you along the way if you're interested.

**Comment by levtomer66** [comment]
@aantn Yes I would love to

**Comment by aantn** [comment]
@levtomer66 reaching out to you on the Slack community.
