### ISSUE TITLE
Improve the Change Tracking Page

### ISSUE THREAD

**Issue by kumarankit999** [robusta-dev/robusta#1138]
**Describe the bug**
The Top navbar Section is overlapped and looks to be merged by its text on https://home.robusta.dev/features/change-tracking

**To Reproduce**

**Expected behavior**
It should have some space in between them, have some distance between them.

**Screenshots**
![image](https://github.com/robusta-dev/robusta/assets/111564362/b618e983-e197-4ba4-9f13-be5276b613e5)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [22]

**Comment by aantn** [comment]
Thanks for reporting. Working on a fix!

**Comment by aantn** [comment]
We've fixed it. Thank you again for reporting!
