### ISSUE TITLE
Improve runner service monitor in order to be useful for external prometheus 

### ISSUE THREAD

**Issue by michMartineau** [robusta-dev/robusta#1151]
**Is your feature request related to a problem?**
When a external embedded prometheus is used in order to scrape runner metrics, instead of the embedded one, it is not ever  possible to use the service monitor defined for the runner.

**Describe the solution you'd like**
We would like to add additional labels on the service monitors. This labels could be needed for prometheus to see the service monitor. We would like also to add other capabilities like relabeling, metrics relabeling..

**Additional context**
I propose the pull request https://github.com/robusta-dev/robusta/pull/1150

**Comment by pavangudiwada** [comment]
Thanks again! Closing based on #1150
