### ISSUE TITLE
[Helm] chart can't be install without defining .Values.rsa or .Values.rsa.existingSecret

### ISSUE THREAD

**Issue by michMartineau** [robusta-dev/robusta#1160]
**Describe the bug**
commit https://github.com/robusta-dev/robusta/commit/6ee8d1fdcaae5ef6b6c632cda2a76327e9a2f819 introduced .Values.rsa.existingSecret.  
It is not possible anymore to install the chart without defining rsa.

As .Values.rsa is nil by default,  and it is a parent of existingSecret, the following change (runner.yaml) fails.
```
secretName: {{ default "robusta-auth-config-secret" .Values.rsa.existingSecret }}
```
**To Reproduce**
- install the chart without defining   .Values.rsa or .Values.rsa.existingSecret

**Expected behavior**
The chart should be installed without .Values.rsa or .Values.rsa.existingSecret defined

**Additional context**
Proposal: https://github.com/robusta-dev/robusta/pull/1161

**Comment by pavangudiwada** [comment]
Closing since its merged #1161
