### ISSUE TITLE
Improve the Jira Sink

### ISSUE THREAD

**Issue by paoloyx** [robusta-dev/robusta#1163]
**Is your feature request related to a problem?**
Jira integration is very useful, albeit a bit basic in its current form. I would love Robusta to have some adding features like:

* Closing Jira issues when a matching solved alert is fired
* Configure Jira Sink behavior through additional params (i.e. send resolved status to Jira, re-open closed issues if new alarms arrive, etc. etc.)
* Update existing issues with new content from Prometheus alerts (if alert's fingeprint matches)
* Carry on additional fields coming from Prometheus alerts (i.e. `runbook_url` above the others)

**Describe the solution you'd like**
The overall flow is the one depicted here
![image](https://github.com/robusta-dev/robusta/assets/991842/d5d002b7-5057-49bc-9ab9-92ebabe3a27c)

In a nutshell, when a Prometheus alerts fire:

* If there is NOT a matching Jira issue, create a new Jira issue
* If there is a matching Jira issue that is not in DONE status, then:
   * Mark the issue is Done if alert is resolved AND Robusta is configured to send resolved status to Jira
   * Update issue summary/description if alert is not resolved
* If there is a matching jira issue in DONE status, then:
   * If alert is resolved, there is nothing to do as Jira issue is already done
   * If alert is not resolved then:
      * If re-open issue behavior is active, re-open DONE issue
      * Create a new issue otherwise

**Describe alternatives you've considered**
I did not found alternatives in Robusta codebase, I was more or less used to what another project does for Prometheus ([jiralert](https://github.com/prometheus-community/jiralert)) and I'd like to implement them in Robusta

**Comment by aantn** [comment]
This makes a lot of sense, thank you. The diagram is especially helpful.

We will review in more depth soon.

**Comment by arikalon1** [comment]
Thanks for the PR @paoloyx
