### ISSUE TITLE
UI Bug - Incorrect Robusta Version on cluster

### ISSUE THREAD

**Issue by tip-dteller** [robusta-dev/robusta#1214]
**Describe the bug**
UI displays incorrect version even though image and chart are different

**To Reproduce**
No idea how, it just appears like that...

**Expected behavior**
UI should display correct image

**Screenshots**
![image](https://github.com/robusta-dev/robusta/assets/128965284/c0141f0e-ee5f-4e6a-8200-8ebf3f6ff9e0)

```
kgp robusta-runner-766d6956ff-zx5ww -o yaml | yq '.spec.containers[].image'         
us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:0.10.26

helm ls
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
robusta default         93              2023-12-14 11:13:37.04453 +0200 IST     deployed        robusta-0.10.26 0.10.26    

```

**Comment by aantn** [comment]
@tip-dteller hey, is this still occruing?

**Comment by tip-dteller** [comment]
it occurs randomly:
but appears to have this frequency pattern:
* after helm chart version upgrade - more frequent.
* after `kubectl rollout restart deployment robusta-runner` - on a rare occasion

**Comment by aantn** [comment]
Thanks. How long does the incorrect version persist after updating the Helm chart or doing the restart?

**Comment by aantn** [comment]
@tip-dteller is this still occuring?

**Comment by d-teller** [comment]
Can close this. Think it happened on a specific version and hasnt since.
