### ISSUE TITLE
Robusta / KRR bug when passing prometheus_auth

### ISSUE THREAD

**Issue by Timeraa** [robusta-dev/robusta#1251]
**Describe the bug**
Using the hem chart with `globalConfig.prometheus_auth` and a value of "Basic <base64 string>" krr can't run and errors with `Got unexpected extra argument` because it doesn't wrap the `prometheus_auth` value in quotes when running the krr job

If I wrap it in quotes something else in robusta itself errors so this is an issue in the passing of robusta to krr when an efficiency scan is being run

**To Reproduce**
1. Setup robusta
2. have prometheus behind authentication with nginx for example and basic auth (should error with normal Bearer as well)
3. Pass `globalConfig.prometheus_auth` in the helm values (`generated_values.yaml`)
4. Install / Upgrade robusta
5. Run a KRR scan (Efficiency report) from the UI
6. Monitor the logs of either robusta or the KRR job itself and see that the job fails with said error

**Expected behavior**
It should perform the KRR scan without any issues.

**Screenshots**
![image](https://github.com/robusta-dev/robusta/assets/29104008/16109e64-4e05-4019-8e0a-5d2e98fe3c72)

Robusta version used is: 0.10.27 using the helm chart

**Comment by arikalon1** [comment]
Thanks for reporting it @Timeraa 

Just to be clear, the value you're putting in `globalConfig` is in the format of `prometheus_auth: Basic XXXX` ?

**Comment by Timeraa** [comment]
> Thanks for reporting it @Timeraa 
> 
> 
> 
> Just to be clear, the value you're putting in `globalConfig` is in the format of `prometheus_auth: Basic XXXX` ?

Yes correct!

**Comment by RobertSzefler** [comment]
After investigating the issue, it appears that the issue might be due to an older version of Robusta being used.

We recommend your upgrading to the newest version, this should fix your problem.

**Comment by Timeraa** [comment]
Yeah I noticed you guys fixed in a recent version, so I assume we can close this issue for now. I guess no one kept track of this issue existing before fixing it?
