### ISSUE TITLE
Adding Argo Rollout Type in Apps Page

### ISSUE THREAD

**Issue by satheeshprabhakaran** [robusta-dev/robusta#1253]
**Is your feature request related to a problem?**
Yes its related argo rollouts. Argo Rollout is CRD from argo tools to have better deployment process. I feel worried since I am not able to see in Robusta UI

**Describe the solution you'd like**
Adding Argo Rollout CRD in Apps Page

**Describe alternatives you've considered**
We have considered alternative tools like Grafana, Datadog, Newrelic

**Additional context**
![image](https://github.com/robusta-dev/robusta/assets/110389129/ddc17f59-4c95-483c-b9ad-c44014416193)

**Comment by RoiGlinik** [comment]
Hey @satheeshprabhakaran ,
It is now supported in Robusta 0.11.0. 
Please add to your `generated_values.yaml` file

`argoRollouts: true`
