### ISSUE TITLE
Document/prevent naming collision for playbooks 

### ISSUE THREAD

**Issue by ionfury** [robusta-dev/robusta#1256]
Following the [wonderful documentation](https://docs.robusta.dev/master/playbook-reference/actions/develop-actions/playbook-repositories.html) to create my own playbook actions, I foolishly chose the name "robusta_playbooks" in my `pyproject.toml`.  Robusta successfully loaded this new playbook, however it overwrote the existing playbook library and began crash looping.

This is a pretty easy way to shoot yourself in the foot and might be worth a note in the documentation or some warning/way to prevent someone as foolish as myself from doing the same thing.

**Comment by pavangudiwada** [comment]
@ionfury :sweat_smile: Interesting issue. We are fixing it asap
