### ISSUE TITLE
Add configurable priority class as part of the helm chart template

### ISSUE THREAD

**Issue by dzliang100** [robusta-dev/robusta#1266]
**Is your feature request related to a problem?**
Please describe a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
I'd like to have a way from the helm chart to change the priority class for the Robusta runner and forwarder pods.

**Describe the solution you'd like**
A priorityClassName field should be added in the helm values.yaml file under both the kubewatch and runner sections, as well as added to the forwarder and runner templates.

**Describe alternatives you've considered**

**Additional context**

**Comment by arikalon1** [comment]
Thanks for the PR @dzliang100 
Closing it
