### ISSUE TITLE
Missing Dockerfile for Grafana-Renderer?

### ISSUE THREAD

**Issue by Shamim56** [robusta-dev/robusta#1381]
hello,

im trying to understand the usage of grafana-renderer found in the [helm chart](PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser). I believe it is disabled by default but i also do not understand the usecase

i also could not find the dockerfile for the supposed image, and the image uploaded is over a year old on ghcr so i was not sure if something like this is maintained and if i should be using the image

thanks !

**Comment by arikalon1** [comment]
Hi @Shamim56 ,

The Grafana renderer can be used to render Grafana dashboards and send it as a notification.

The implementation of it can be found here:
https://github.com/robusta-dev/robusta-puppeteer

This `action` for example uses it: https://github.com/robusta-dev/robusta/blob/b2348bb346e34e05a9d44b376f4a47241441061d/playbooks/robusta_playbooks/deployment_status_report.py#L44

The typical use case is sending some Grafana dashboards after a deployment was created

Does that help?

**Comment by Shamim56** [comment]
Yes it makes sense now, thank you. I think that link for the implementation is private, it returns a 404

**Comment by arikalon1** [comment]
you're right @Shamim56 
I made it public
