### ISSUE TITLE
Example Java jmap and stack fails

### ISSUE THREAD

**Issue by ThommyH** [robusta-dev/robusta#1469]
**Describe the bug**
Running the example from https://docs.robusta.dev/master/tutorials/application-troubleshooting-java.html with a fresh installation doesnt work.

**To Reproduce**
Install robusta with helm connect tot slack. Follow https://docs.robusta.dev/master/tutorials/application-troubleshooting-java.html
```
kubectl apply -f https://raw.githubusercontent.com/robusta-dev/java_toolkit/416d62ba6a6c6cb2e5270c4cf793d340b708b9ea/java_test_pod/test_pod_config.yaml --namespace=test
robusta playbooks trigger java_process_inspector name=test-java-pod namespace=test
```
Click on jmap in slack.

Receiving error in slack:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/robusta_playbooks/java_pod_troubleshooting.py", line 127, in run_jdk_command_on_pid
    jdk_output = run_java_toolkit_command(jdk_cmd, pod, custom_annotations=params.custom_annotations)
TypeError: run_java_toolkit_command() missing 1 required positional argument: 'override_jtk_image'
```

**Expected behavior**
Should work

**Comment by aantn** [comment]
Wonderful, happy to hear it!
