### ISSUE TITLE
Specify the cluster name in Slack messages

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#152]
In default messages we send to Slack, we should specify the cluster name. This is important for multi-cluster environments / environments with more than one AlertManager.

We should make sure that we send the cluster name for:

1. Crashloop notifications
2. Prometheus alerts

If possible, it would be nice to let users customize our bot-name (Robusta) or at least to specify the cluster name there too.

Thanks again to @tim-sendible for the feedback

**Comment by aantn** [comment]
@arikalon1 did we fix this yet?

**Comment by arikalon1** [comment]
yes. fixed in 0.8.18
