### ISSUE TITLE
additional_env_vars naming

### ISSUE THREAD

**Issue by lssjbrolli** [robusta-dev/robusta#1594]
**Describe the bug**
runner uses additional_env_vars, but holmes uses additionalEnvVars

**Expected behavior**
we should use the same name for consistency

**Additional context**
also on docs https://docs.robusta.dev/master/configuration/ai-analysis.html#sinks-configuration-secrets it says to use additional_env_vars to set ROBUSTA_UI_TOKEN but that won't work

**Comment by RoiGlinik** [comment]
Hey @lssjbrolli I have fixed our docs.
Added support for snake case in holmes as well.
