### ISSUE TITLE
Alert is still firing in Robusta UI

### ISSUE THREAD

**Issue by slitsevych** [robusta-dev/robusta#1654]
Greetings!
I might be facing something very trivial here, but I've not figured this out yet. 

The situation is that I'm still seeing an alert "**pod_container_terminated**" (reporting on a previously terminated "robusta-runner" pod) that's still firing in Robusta UI but which was resolved in Alertmanager immediately after rolling out a new deployment/pod. 
So at this point I'm not sure how to make Robusta sync the actual state of alerts or at least "forget" this one. 

Please let know what am I missing here and/or are there any additional details I need to provide?

Thanks in advance

**Comment by arikalon1** [comment]
hi @slitsevych 

Thanks for reporting this
If an alert isn't retransmitted for more than 6 hours, it will be considered resolved.
This is in order to handle cases, where the resolve event is missing.

Is it still firing in your UI account?

**Comment by slitsevych** [comment]
@arikalon1 oh, ok, got it! 
and nope, it's no longer firing, however I need to mention that I decided to rename the alert thus "forcing" it to be thrown away.
