### ISSUE TITLE
New Sink: ntfy.sh

### ISSUE THREAD

**Issue by stephanGarland** [robusta-dev/robusta#181]
**Is your feature request related to a problem? Please describe.**
I'd like an additional sink, and one that's very extensible.

**Describe the solution you'd like**
I use [ntfy.sh](https://ntfy.sh) for push notifications to my phone. It accepts PUT/POST to an endpoint, and then pushes them to the subscriber. I suspect there are other tools that would also accept a simple payload that could make use of this kind of output.

**Comment by aantn** [comment]
Yeah, we can do this. Would you be able to help beta test it?

@arikalon1 Can we do this right after we finish the Telegram sink?

**Comment by stephanGarland** [comment]
Yes, absolutely. I just found Robusta yesterday and plan on installing it into my homelab later this week.

**Comment by arikalon1** [comment]
sure. We'll start implementing it soon.
