### ISSUE TITLE
Add a button to the README page for our Slack community

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#195]
Title says it all. It should match the other badges already there.

**Comment by 852hamza** [comment]
yes i can 
can u assign me

**Comment by aantn** [comment]
Of course! Thank you!

**Comment by 852hamza** [comment]
how can i run this  locally  and what changing occure

**Comment by aantn** [comment]
You can fork this repo and make changes. Push the changes to your fork on GitHub and check the README.md file in your fork.

**Comment by kranurag7** [comment]
@852hamza Are you still working on the issue? Please let me know.

**Comment by pavangudiwada** [comment]
Seeing this just now. This PR https://github.com/robusta-dev/robusta/pull/289 resolves this issue.

**Comment by aantn** [comment]
@pavangudiwada thanks, closing
