### ISSUE TITLE
Add an edit on GitHub button to each page in the docs

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#196]
Goal is to make it easier for people to submit contribution to the docs. Many people don't understand today that the docs are open source.

Thank you to @Sayanta66 for the idea!

**Comment by rakshitgondwal** [comment]
Hey! Is this open for grabs?>

**Comment by aantn** [comment]
Hey, we're soon going to merge a major overhaul of the docs that changes
the sphinx theme, so another issue would be a better choice right now
