### ISSUE TITLE
Improve Sinks Documentation

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#203]
Today our sinks are documented in two places:

1. [On the *Sinks* page (and subpages of it)](https://docs.robusta.dev/master/catalog/sinks/index.html)
2. [On the *Configuration Guide* page](https://docs.robusta.dev/master/user-guide/configuration.html#defining-additional-sinks)

I've seen a few people confused by this. They go to the Sinks page and read that we support, e.g., Kafka but they can't find details on how to configure Kafka.

I suggest we move the details on how to configure each sink out of the *Configuration Guide* page (the 2nd page mentioned above) and into a unique page for each sink. Each sink should have a subpage under the *Sinks* page and it should have both the screenshot and the details on yaml configuration.

@arikalon1 wdyt?

**Comment by kranurag7** [comment]
Looks good to me. If we will create different pages for different sinks then we can also add recommendation and best practices related to that particular sink.

**Comment by aantn** [comment]
@kranurag7 thanks for the feedback. Feel free to open a PR if you have time to work on this

**Comment by pavangudiwada** [comment]
Each sink has its own page with details about it. https://docs.robusta.dev/master/catalog/sinks/index.html Is there anything else to add?

**Comment by kranurag7** [comment]
I think as of now everything is looking good. One improvement we can do is that we can add how to set up webhook URL for that particular sink.

**Comment by aantn** [comment]
@pavangudiwada yeah I think we're good.

@kranurag7 do you mean for the MSTeams sink? For something else?

**Comment by kranurag7** [comment]
Yes @aantn I was talking about MS Teams webhook URL. Similarly, we can do
the same for other sinks as well, in which it's missing. In some of the
sinks we have mentioned it (like in case of telegram, we have mentioned how
to obtain the chat ID)

**Comment by aantn** [comment]
I've added a Loom showing how to obtain the webhook on MS Teams.

https://docs.robusta.dev/master/catalog/sinks/ms-teams.html?highlight=ms%20teams#creating-a-webhook-url-in-ms-teams

I'm closing this for now, but if you have further ideas please open a new issue. Thanks everyone for the help.
