### ISSUE TITLE
Add playbook action to monitor changes to ClusterRoleBindings

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#217]
**Motivation**
It is useful to track changes to ClusterRoleBindings to stay on top of who has what permissions.

**Suggested Feature**
Robusta already has triggers for ClusterRoleBinding changes (see [docs](https://docs.robusta.dev/master/catalog/triggers/kubernetes.html)) but there are no builtin actions setup for those triggers. We should add an action called `cluster_permissions_watcher` which notifies when ClusterRoleBindings change and outputs summarized information about the change.

**Alternatives**
You can monitor ClusterRoleBindings today using the `resource_babysitter` action (see [tutorial](https://docs.robusta.dev/master/tutorials/configuring-automations.html) and [docs](https://docs.robusta.dev/master/catalog/actions/change-tracking.html#resource-babysitter)) but the output there is very generic and technical. (It just shows a diff.) If we are going to implement an action for this it should be optimized for ClusterRoleBindings and print more useful data like "The ClusterRole named XYZ now has permission to...."

**Comment by wahajXgrid** [comment]
hey team, I am working on this issue.
