### ISSUE TITLE
Using playbooksRepos causes error: "coalesce.go:163: warning: skipped value for playbookRepos: Not a table."

### ISSUE THREAD

**Issue by arikalon1** [robusta-dev/robusta#236]
Trying to enable git playbooks in my private `generated_values.yaml` file causes an error
coalesce.go:163: warning: skipped value for playbookRepos: Not a table.

1. in the `generated_values.yaml` file add:
```
playbookRepos:
  some_git_playbooks:
    url: "git@github.com:robusta-dev/my-playbooks.git"
```
2. run `helm instal robusta ...`

**Expected behavior**
The git playbooks repo should be installed and loaded into Robusta runner

**Comment by aantn** [comment]
Is there any chance that's a spacing/tabs issue? Something here is invalid from helm's perspective.

**Comment by arikalon1** [comment]
it's the default initialization of the `playbookRepos` values to [], but it's a dictionary.
