### ISSUE TITLE
`robusta playbooks push` fails if robusta is installed in namespace other than default and namespace is not specified

### ISSUE THREAD

**Issue by avinashupadhya99** [robusta-dev/robusta#239]
**Describe the bug**
`robusta playbooks push` fails if robusta is installed in a namespace other than the default namespace and the `--namespace` flag is not specified. Since it is not recommended to have pods in the default namespace, it is common to install robusta in its own namespace.

**To Reproduce**
1. Install robusta in a namespace other than the default using `helm install robusta robusta/robusta -f ./generated_values.yaml -n robusta --create-namespace`
2. Create a custom playbook repository by following https://docs.robusta.dev/master/developer-guide/actions/playbook-repositories.html
3. Load the playbook using `robusta playbooks push ./my-playbooks-project-root`
4. See an error

**Expected behavior**
An appropriate error should be displayed instead of the python erorr.

**Errors**
```
======================================================================
Uploading playbooks code...
======================================================================
No resources found in default namespace.
======================================================================
Runner pod not found.
======================================================================
======================================================================
Fetching logs...
======================================================================
Error from server (NotFound): deployments.apps "robusta-runner" not found
Traceback (most recent call last):
  File "/home/avinashupadhyaya/.local/bin/robusta", line 8, in <module>
    sys.exit(app())
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/robusta/cli/playbooks_cmd.py", line 84, in push
    return
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/home/avinashupadhyaya/.local/lib/python3.9/site-packages/robusta/cli/utils.py", line 93, in fetch_runner_logs
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kubectl logs  deployment/robusta-runner -c runner --since=1s' returned non-zero exit status 1.
```

**Robusta version**

```
robusta version
version 0.8.26
```

**Additional context**

**Sorry, I opened the issue without checking for the namespace flag**. I found the namespace flag but would like appropriate error messages to be displayed if possible.

**Comment by aantn** [comment]
+1

If the pod doesn't exist then we should say so and recommend using the namespace flag if necessary. No need for a long exception.

@avinashupadhya99 any interest in working on a PR for this?

**Comment by avinashupadhya99** [comment]
I just realized that the exception logs are from the `Fetching logs...` section, which is displayed for both positive and negative scenarios. Should we not display logs if the command fails? Or should I just update the error message suggesting to use a namespace flag if the robusta-runner pod does not exist?

Looking at the logs for a new user, it feels like the command crashed and printed exceptions but it is by design to print the logs. Should we display the logs in case of exceptions?

**Comment by aantn** [comment]
I think there are two issues here that should be fixed:

1. If the runner pod doesn't exist then `fetch_runner_logs` throws an exception. It would be better if it just printed something like "Cannot fetch logs. robusta-runner not found."
2. In the `push` command we should check if the runner pod exists. If not, we can print an appropriate message suggesting you set `--namespace` and exit. (I don't think it matters in this case if we call `fetch_runner_logs` or not because after fix 1 that will just print `"Cannot fetch logs. robusta-runner not found."` which is fine.)
