### ISSUE TITLE
Playbooks pushed to namespace other than default are not present in `robusta playbooks list`

### ISSUE THREAD

**Issue by avinashupadhya99** [robusta-dev/robusta#243]
**Describe the bug**
Playbooks pushed to namespace other than default are not present in `robusta playbooks list`

**To Reproduce**
1. Install robusta in a namespace other than the default using `helm install robusta robusta/robusta -f ./generated_values.yaml -n robusta --create-namespace`
2. Create a custom playbook repository by following https://docs.robusta.dev/master/developer-guide/actions/playbook-repositories.html
3. Load the playbook using `robusta playbooks push ./my-playbooks-project-root --namespace robusta`
4. Run `robusta playbooks list --namespace robusta | grep 'my_action'`, it returns nothing.

**Expected behavior**
The custom playbook pushed should be present in the list of playbooks returned by `robusta playbooks list --namespace robusta`

**Screenshots**
![image](https://user-images.githubusercontent.com/52544819/155535155-b9ca3f9e-2512-43b2-b7eb-e6abfc61202d.png)
Happy to provide the contents of `pyproject.toml` and the file in `my_action`

**Robusta version**

```
robusta version
version 0.8.26
```

**Additional context**
N/A

**Comment by avinashupadhya99** [comment]
Closing this since I had not included the playbook in my values.yaml file and upgraded the helm chart. Once included in the YAML file and `helm upgrade` is run, I am able to see the playbook in `robusta playbooks list`

**Comment by aantn** [comment]
Cool, glad it works :)
