### ISSUE TITLE
More details on 'Crashing pod' Slack message

### ISSUE THREAD

**Issue by shfisher** [robusta-dev/robusta#260]
I have amount of containers inside the pod, and when the pod crashed I want to see in the Slack message which container exactly caused it. For example, my workflow is to launch some init containers before the pod starts (fetch secrets, internal dependencies, flyway), and for now I get the same message 'Crashing pod <pod name> in namespace <namespace>', and I need to describe the pod to understand which container failed. I want to look ah the message and immediately know - ah, it's flyway problem, no panic.

**Comment by arikalon1** [comment]
Hi @shfisher ,
We display the container name in the message body.
Would adding it to the description as well help? (This way you can see it when hovering on the timeline in the UI)

**Comment by arikalon1** [comment]
I actually think it might be useful for others as well, so I'm going to add it anyway

**Comment by RoiGlinik** [comment]
@arikalon1 I think you have already done it ? can you close this?

**Comment by arikalon1** [comment]
@RoiGlinik yes, closing
