### ISSUE TITLE
Get visibility for ingresses

### ISSUE THREAD

**Issue by orclassiq** [robusta-dev/robusta#261]
Currently I can't use robusta to get notifications about ingresses.
I would like to get notifications about ingresses (or other resources) the same way I get them about pods.

**Comment by aantn** [comment]
We can add something. Would you like to see notifications in Slack or in the UI? If in the UI, where would you expect the changes to appear? Just on the global timeline?

**Comment by orclassiq** [comment]
Ideally, it would appear in both places.
The main point is that there are cluster "error" events that don't appear anywhere in robusta.

**Comment by aantn** [comment]
Closing this, as we now show ingress changes on the UI's timeline
