### ISSUE TITLE
Remember namespace and cluster in UI

### ISSUE THREAD

**Issue by shfisher** [robusta-dev/robusta#262]
When I logout/login to UI, I need to select the cluster and namespace (instead of default ALL). I want to configure what are my default cluster and namespace to show, and at least to remember the last choose

**Comment by aantn** [comment]
Good idea.

I've deployed a quick-fix for now. If you select a namespace and cluster then it will update the URL. If you bookmark that URL and use it next time you login, it will "remember" the settings and use whatever is in the URL.

Let me know if this workaround is useful until we implement a full fix.

@mershal FYI

@liorfranko might be useful for you too

**Comment by aantn** [comment]
@mershal did we fix this?

**Comment by aantn** [comment]
We support presets in the UI that can be used to save filters. Closing but feel free to re-open if you need further help or want additional features.
