### ISSUE TITLE
Kubernetes Events Either coming delayed or incorrectly

### ISSUE THREAD

**Issue by NikhilMaheshwari** [robusta-dev/robusta#272]
**Describe the bug**
Feature of kubernetes events to slack sink is showing events which when we trace back on cluster are missing. 
So for event notification that are not containing tabular event data in alert, If we cross check events in kube cluster via command

kubectl get events -A

Those events are missing in output of that. Same is case in describe pod output. But events are shown on robusta. So seems wrong events are triggered here.

**To Reproduce**
1. Enable slack sink for platform runbooks
2. Trigger some events on a pod
3. Validate the event got in slack. If event does not contain the tabular event data, check it's kube events via kube console
4. Events would be missing in Kube but are shown on robusta

**Expected behavior**
That alert should not have been triggered given that there is no event on cluster supporting that

**Comment by aantn** [comment]
@arikalon1 is this the bug you found regarding event deletions?

**Comment by arikalon1** [comment]
@aantn yes, it is.
The fix is included in release 0.9.0.
Closing
