### ISSUE TITLE
Resolved Alertmanager alerts are fired against the sink

### ISSUE THREAD

**Issue by michelesr** [robusta-dev/robusta#274]
**Describe the bug**
Alerts in `resolved` status are sent again to the sinks, giving the wrong impression that the problem hasn't been resolved.

**To Reproduce**
1. Trigger a Prometheus alert
2. Resolve that alert
3. Check against the main sink

**Expected behavior**
Either the alert shouldn't be fired again, or it should be labeled in a way that makes clear that the problem has been resolved

**Screenshots**
![screenshot-2022-03-17-12:49:35](https://user-images.githubusercontent.com/2516077/158812018-34280382-0c2d-4876-a248-c12432944c1b.png)
A duplicate alert, where the 2nd message is from the resolved alert in Prometheus

**Comment by aantn** [comment]
Yeah, that's a bug.

My preference is to not send a message the second time at all. @arikalon1 what are your thoughts?

@michelesr This is slightly off-topic, but we're planning to do some work around alert lifecycle in the UI. If the same alert fires multiple times, we'd like to show those firings as one continously firing alert, not several distinct alerts. When the alert is finally resolved we'd like to also show that and mark the alert as closed. Do you have any thoughts about this? Other than fixing this bug, are there other features you'd like to see regarding alert lifecycle in either the UI or Slack?

**Comment by michelesr** [comment]
Maybe implement a repeat interval like in Alertmanager?

**Comment by aantn** [comment]
Yeah, perhaps we could do it with better rate limiting (as part of the trigger) or some form of rate limiting on the sink.

**Comment by arikalon1** [comment]
I think we should add the alert status (firing / resolved) and send it to sinks, similarly to what alert manager does.
I think repeat interval/rate limiting applies on the same alert, but if the alert status has changed from firing to resolved the rate limiting shouldn't silence it.

**Comment by aantn** [comment]
@arikalon1 if we do that, how do we address the original issue here? By filtering out resolved alerts in the Slack sink?

**Comment by aantn** [comment]
Got it. This sounds good to me.

**Comment by aantn** [comment]
@michelesr hey, we're going to fix this in the current sprint.

**Comment by Sheeproid** [comment]
@michelesr we added a fix tha labels the alert as resolved.
You're more then welcome to share more feedback with us 🙂
