### ISSUE TITLE
Add --context flag to all robusta cli commands to run them on a given kube config context

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#277]
E.g. `robusta gen-config --context=other-cluster`

**Comment by aantn** [comment]
I think we can leave the docs as is. We should add the flag to the python code for the cli.

**Comment by kingsathurthi** [comment]
Okay, it would be great if you let me know that path to python file

**Comment by kranurag7** [comment]
@kingsathurthi Here is the link to the CLI code https://github.com/robusta-dev/robusta/tree/master/src/robusta/cli

**Comment by AvineshTripathi** [comment]
Hey @kingsathurthi if you are not working on this issue, can I take over this

**Comment by kingsathurthi** [comment]
@AvineshTripathi I'm working on this issue

**Comment by AvineshTripathi** [comment]
@kingsathurthi we can always collaborate for the issue if you want

**Comment by kingsathurthi** [comment]
Sure @AvineshTripathi how do we connect?

**Comment by AvineshTripathi** [comment]
Slack my handle is Avinesh Tripathi in slack
