### ISSUE TITLE
`annotations` / `tolerations` / `nodeSelector` support in helm charts

### ISSUE THREAD

**Issue by SohumB** [robusta-dev/robusta#279]
For easier integration into differing environments, it'd be great if these parts of the pod template spec for individual deployments were customisable!

It's possible to work around this with anything that can patch post-helm-rendered yamls, like:
* `kustomize`
* `kustomize` as used by `helmfile`'s `strategicMergePatches` key
* `kustomize` as used by `helm` 3's new [post-renderer support](https://helm.sh/docs/topics/advanced/#post-rendering)

**Comment by arikalon1** [comment]
@SohumB Thanks for reporting this. 
Makes perfect sense, we'll add it shortly
