### ISSUE TITLE
Only monitor default namespace

### ISSUE THREAD

**Issue by acrogenesis** [robusta-dev/robusta#300]
Is there a way to only monitor the default namespace?

**Comment by arikalon1** [comment]
Hi @acrogenesis ,
Can you elaborate a on what you mean by monitoring?
Are you interested in only receiving Slack/Teams notifications for a specific namespace or is your goal to limit which namespaces Robusta itself monitors (e.g. for security reasons)

**Comment by aantn** [comment]
@acrogenesis can we close this? Did that address your issue?

**Comment by acrogenesis** [comment]
Yes, thanks!
