### ISSUE TITLE
How to setup multiple sink's of same type (ms teams)

### ISSUE THREAD

**Issue by mvkrishna86** [robusta-dev/robusta#336]
I would like to setup multiple msteams sinks. For example, all crashloopback errors should go to one channel and all deployment changes should go to another channel.
Also, I am interested in only few namespaces, anything happens in ns1, ns2 are important for me, so would like to send notifications and take actions on them.

**Comment by Sheeproid** [comment]
About your first question, I think this is possible, please take a look at the following and see if in answers your questions
1. https://docs.robusta.dev/master/catalog/sinks/index.html
2. https://docs.robusta.dev/master/user-guide/configuration.html#sink-matchers

About the  second issue, can you please open a different issue for that?
