### ISSUE TITLE
Add nodeSelector and affinity in values.yaml

### ISSUE THREAD

**Issue by mvkrishna86** [robusta-dev/robusta#340]
Please add affinity and nodeSelector in the values.yaml for both forwarder and runner. Now, after every change, I had to edit the deployment manually and add nodeSelector and affinity to get robusta pods scheduled on k8s.

**Comment by Sheeproid** [comment]
Hey @mvkrishna86 , just to clarify, you tried to follow the instructions in the docs: https://docs.robusta.dev/master/user-guide/configuration.html#deploying-robusta-on-specific-nodes and it did not work?

Also, I see that we have a lot of discussions here, maybe you can join to [Robusta Slack Community](https://join.slack.com/t/robustacommunity/shared_invite/zt-18x24hrz4-1SQQCSa~AF9LgTYFwA6cag) and write in the #support channel? it will make the discussions easier :)

**Comment by Sheeproid** [comment]
nodeSelectors will be added on the next release of Robusta (0.9.12 and up)

**Comment by Avi-Robusta** [comment]
we added it to robusta (just didn't close it here yet)
https://docs.robusta.dev/master/user-guide/configuration.html?highlight=nodeselector#deploying-robusta-on-specific-nodes
