### ISSUE TITLE
New Sink: Webex

### ISSUE THREAD

**Issue by fferraro87** [robusta-dev/robusta#343]
**Describe the solution you'd like**
In our company we're using webex instead of slack so it will be fantastic if robusta support sink also on webex for us

**Comment by Sheeproid** [comment]
Hey @fferraro87 , this is a great idea and we will add it soon.
Do you have an example of another tool that you use in your company that you like their webex integration and why?

Also, Can I ask what types of messages are you interesting on sending there (alerts, crashing pods, etc)?

**Comment by alikhanxgrid** [comment]
Working on this issue
