### ISSUE TITLE
New sink: email

### ISSUE THREAD

**Issue by gioppoluca** [robusta-dev/robusta#363]
**Is your feature request related to a problem? Please describe.**
An email sink is an "evergreen" good for all needs.
Also it could be interesting to be able to have the option to get the mail to use from a namespace label
**Describe the solution you'd like**
Since we use namespaces to isolate projects we need to send emails to team mail
There should be the need to send the mail accordingly to the namespace that originated the problem

**Describe alternatives you've considered**
no other alternative are available

**Additional context**
Do not still know well this product but it seems that sink are cluster level and there is no distinction on who receive what so a more granular approach is required with this sink request

**Comment by gioppoluca** [comment]
Any news on this issue, can you share a milestone for having the email sink?

**Comment by Sheeproid** [comment]
Hey @gioppoluca! We got several requests for sinks lately, and they are in the works. We're considering using an open-source library called [Apprise](https://github.com/caronc/apprise), or implementing it ourselves.

It will still might take some time. Can we help with a workaround meanwhile?

**Comment by alikhanxgrid** [comment]
working on this issue

**Comment by Sheeproid** [comment]
will be included in the next version of Robusta
