### ISSUE TITLE
Add Job failure trigger

### ISSUE THREAD

**Issue by anggutie-dev** [robusta-dev/robusta#382]
Hello,

We started using Robusta.dev a couple of days ago and so far we love it, we are actively testing the python profiler and the monitoring + slack notifications.

Notifications/alerts work great with deployments, statefulsets, etc but unfortunately this is not the case for Jobs. We need to receive an alert as soon as a Job fails.

It would be great if you can include an "on_job_failure" trigger and get the same notification format as deployment pods.

I'm leaving this slack thread for more information if needed: https://robustacommunity.slack.com/archives/C030R8AN84D/p1655314960039229

**Comment by arikalon1** [comment]
Thank you for reporting this @anggutie-dev , and thank you for the kind words!

It sounds like a useful trigger.
We will try to prioritize and implement it shortly.

**Comment by arikalon1** [comment]
@anggutie-dev , this was merged to 0.10.0
