### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by bishal7679** [robusta-dev/robusta#394]
![Screenshot (145)](https://user-images.githubusercontent.com/70086051/174719251-3aab58db-0622-4bdd-89d3-1901c8d25fa0.png)

**Comment by Sheeproid** [comment]
Hey @bishal7679 , thanks for flagging.

Is acknowledgements a typo?

**Comment by bishal7679** [comment]
@Sheeproid yes you are right. I said a/q outside american.

**Comment by bishal7679** [comment]
Thanks for helping

**Comment by Sheeproid** [comment]
@bishal7679 Thanks for trying to help. It is most appreciated.

Can I help in anyway in the process of trying out Robusta? Do you have any feedback?
