### ISSUE TITLE
Debugger pod's doesn't have privileged RBAC permissions

### ISSUE THREAD

**Issue by SamAlex0808** [robusta-dev/robusta#395]
**Describe the bug**
The Debugger pods doesn't have privileged permissions which the robusta-runner has. It uses the default service Account. As debugger pods are an extension of the robusta runner and robsta-runner can delegate action to be run on debugger pods, its is required that they get similar privilege the robust-runner has

**Comment by Avi-Robusta** [comment]
- [ ] TODO: test on kind

**Comment by Avi-Robusta** [comment]
merged
