### ISSUE TITLE
New Sink: Discord

### ISSUE THREAD

**Issue by Joda89** [robusta-dev/robusta#399]
**Is your feature request related to a problem? Please describe.**
I woud like to use discord instead of slack.
I tried to use the webhook but it doesn't work

**Describe the solution you'd like**
it could be great to use discord like slack

**Comment by arikalon1** [comment]
Thank you for reporting this @Joda89 

It's the second time today someone has asked for a Discord sink today.
We're going to implement it soon

**Comment by aantn** [comment]
Hi all, @anFatum has been working on this and we'll be merging it soon.

If you're interested in using it, please provide us with feedback and let us know what you think!

https://github.com/robusta-dev/robusta/pull/460

**Comment by arikalon1** [comment]
Hi @Joda89 
The Discord sink was released as part of version 0.10.1

Any feedback is most welcome

**Comment by Joda89** [comment]
Hi @arikalon1
it works well thank you so much for this function.

Cordially
