### ISSUE TITLE
Use in a normal Docker / bare metal environment?

### ISSUE THREAD

**Issue by binaryfire** [robusta-dev/robusta#407]
Hi guys

Is there a way to use Robusta in a normal Docker / bare metal environment? I couldn't find any info in the docs.

I have a traditional cluster that I'm monitoring with Prometheus which I'd love to use it for.

Cheers

**Comment by arikalon1** [comment]
Hi @binaryfire 

Can you elaborate a little more about the environment you want to monitor, and how you would like to use Robusta with it?

**Comment by binaryfire** [comment]
@arikalon1 Sure thing. Basically it's just a bunch of standalone bare metal machines running a variety of containers. There's no container orchestration. I'm monitoring everything with Prometheus / AlertManager.

Things like Slack integration, triggers like AlertManager, Scheduled, Webhook and Elasticsearch and actions like alert enrichment would be useful in any Prometheus monitoring scenario (not just Kubernetes).

The Kubernetes integration seems fairly deep though. I might be better off rolling my own using https://github.com/adnanh/webhook with something like Ansible. I also need actions for running scripts and sending webhook payloads which I don't think Robusta has.

**Comment by arikalon1** [comment]
Thanks @binaryfire 

You're right, the Kubernetes integration is fairly deep.
Many of the alert enrichments relying on having the involved Kubernetes resource, which won't work in your scenario.

With some decent tweaking, I think you would be able to use Robusta, but I feel it won't be the ideal solution for you.
