### ISSUE TITLE
Robusta in kubernetes v1.23+

### ISSUE THREAD

**Issue by omfurman** [robusta-dev/robusta#411]
**Describe the bug**
I am using GKE and it keeps on complaining about the deprecated api's. I have found the issue back to the robusta-forwarder pods which try to access a deprecated api: 
```pkg/mod/k8s.io/client-go@v0.16.8/tools/cache/reflector.go:96: Failed to list *v1beta1.ClusterRole: the server could not find the requested resource```

**To Reproduce**
1. Go to GKE
2. Use robusta
3. Get the following warning:
![image](https://user-images.githubusercontent.com/90138173/177030217-a55b8c21-f831-4fec-8d62-d9a29b371ab3.png)

**Expected behavior**
Not use the deprecated api.

Is there a new chart supposed to come out soon to suppress this error?

**Comment by arikalon1** [comment]
Hi @omfurman 

Thank you for reporting this.
It will be fixed on the next Robusta release (in a week or so)

**Comment by arikalon1** [comment]
will be included in 0.9.18
