### ISSUE TITLE
without promethues

### ISSUE THREAD

**Issue by azizonick** [robusta-dev/robusta#421]
hi, can i configure robusta to alert me about changes in k8s without protmetheus, if yes how?

**Comment by alikhanxgrid** [comment]
Hi @azizonick  when you run robusta gen-config, Robusta will ask you if you want to setup prometheus stack like this,

> If you haven't installed Prometheus yet, Robusta can install a pre-configured Prometheus. Would you like to do so? [y/N]

Simply answer "N" and Robusta will not setup Prometheus and will send you alert regarding changes in your k8s cluster.

**Comment by RoiGlinik** [comment]
Great answer @alikhanxgrid ,
@azizonick  in the case you already generated the generated_values.yaml file, using gen-config.
You can edit the field , enablePrometheusStack to false and reinstall robusta

**Comment by arikalon1** [comment]
As written above, by default, changes are sent to the Robusta UI, if you're using it.
You can also configure Robusta to send notification on changes to other destinations, like Slack, MSTeams etc. (We call it `sinks`)

@azizonick Can you elaborate a little more about which changes you would like to see, and how would you prefer to consume it?

**Comment by azizonick** [comment]
sure guys, i ve installed robusta on my cluster, so out of the box it show only "crashloopbackoff" errors, and i want to configure it to show others such as deleted created pods cpu and so on, this is question i am asking

**Comment by alikhanxgrid** [comment]
@azizonick 
Robusta works on three main components Triggers, Actions and Sinks. Triggers run your actions when an event happens on your kubernetes cluster and sinks are where you want to get notified about your changes. You can set up your custom playbooks to get notified of changes you want when you update delete or create something in your cluster. Check out [https://docs.robusta.dev/master/catalog/triggers/kubernetes.html](Triggers) available for your Kubernetes cluster and [https://docs.robusta.dev/master/catalog/actions/index.html](Actions) you want to associate with those triggers. 

Robusta have an amazing community which can resolve all your queries you want join it using https://join.slack.com/t/robustacommunity/shared_invite/zt-1c1e842le-SRZNFUHsCp8hO29BixL1fA. 
I'm Muhammad Ali Khan in the Robusta Slack community, you can reach out to me for any help you want also we can setup a Google meet if you want to clear any confusion regarding Robusta.

**Comment by RoiGlinik** [comment]
@azizonick , is there anything else regarding this issue?
