### ISSUE TITLE
Jira integration

### ISSUE THREAD

**Issue by kayahk** [robusta-dev/robusta#463]
**Is your feature request related to a problem? Please describe.**
We want to automate the creation of issues in Jira from specific alerts, in our current use case, these are alerts based on image scan results in ECR. 

**Describe the solution you'd like**
Each alert has a unique `digest` field that could trigger and limit the issue creation at the same time. Maybe even a combination of different fields, like `image_tag` and `severity` could act as a filter for issue creation in Jira.

**Describe alternatives you've considered**
To create our own service, that would automate this or use some existing pipeline integration with JIRA, but Robusta would be waay cooler.

**Additional context**
see screenshot for example alert
<img width="1663" alt="Screenshot 2022-08-02 at 15 03 55" src="https://user-images.githubusercontent.com/80452889/182372053-ac82cfd8-44ba-4bc3-892f-8df971d34cc3.png">

**Comment by arikalon1** [comment]
Thank you for reporting it @kayahk 
Sounds like a useful action.

We'll prioritize and implement it

**Comment by Noamstrauss** [comment]
This feature will benefit us as well.

**Comment by Sheeproid** [comment]
already implemented. https://docs.robusta.dev/master/configuration/sinks/jira.html#jira
