### ISSUE TITLE
Add trigger for deployment updates where an image changes

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#474]
On Slack, @mitin20 asked for the ability to trigger an action when a deployment is updated and the pod's image changes

We might be able to implement this the same way as https://github.com/robusta-dev/robusta/issues/405

**Comment by mvkrishna86** [comment]
@alikhanxgrid , May I know if you have any plans to implement this?

**Comment by alikhanxgrid** [comment]
> @alikhanxgrid , May I know if you have any plans to implement this?

Not at this moment.
Had worked on it but couldn't complete it.

**Comment by arikalon1** [comment]
@aantn this was added on 0.11.0
[change filters](https://docs.robusta.dev/master/tutorials/playbook-track-changes.html#kubernetes-change-tracking-use-cases)
