### ISSUE TITLE
New Sink: Rocket.Chat

### ISSUE THREAD

**Issue by ShiroDN** [robusta-dev/robusta#477]
**Is your feature request related to a problem? Please describe.**
It would be great to have Rocket.Chat sink. Rocket.Chat is an open source alternative to Slack.

**Describe the solution you'd like**
Rocket.Chat has slack compatible webhooks, so it should be similar to it.

**Additional context**
https://rocket.chat/

**Comment by aantn** [comment]
Sounds good, thank you for opening this.

Especially appreciate the comment on Slack-compatible webhooks. That will make implementation much easier. (We're doing something similar for Mattermost very soon.)

**Comment by mhutter** [comment]
It _used_ to be the case that slack integrations worked just fine with Rocket.Chat, so all that was needed was the option to customize the URL. Not sure if this is still the case though.
