### ISSUE TITLE
New Sink: PagerDuty

### ISSUE THREAD

**Issue by taivo123** [robusta-dev/robusta#489]
**Is your feature request related to a problem?**
It would be great to have PagerDuty sink. PagerDuty is an alternative to VictorOps and OpsGenie.

**Additional context**
https://www.pagerduty.com/docs/guides/prometheus-integration-guide/

**Comment by arikalon1** [comment]
Thanks for reporting it @taivo123 

We're doing a lot of work around the sinks, and we'll add PagerDuty as well

**Comment by taivo123** [comment]
Nice @arikalon1, can you ballpark timescale, are we talking weeks, a few months or a year?

**Comment by Sheeproid** [comment]
The honor is yours :)
