### ISSUE TITLE
sticky filter for cluster/namespace/event type

### ISSUE THREAD

**Issue by kayahk** [robusta-dev/robusta#491]
We love working with Robusta on a daily basis while managing multiple clusters. One pain point that we have when using the UI, though, is that we constantly have to narrow down and focus the context by only selecting the clusters/namespaces we are currently interested in.
In our case, when we want to analyse or troubleshoot something, this is usually (>90% of the time) limited to one cluster and/or a selection of namespaces. And for this, we mainly use and switch between Apps and Timeline views. 
BUT, each time we set the filter to see what we would like to see, it gets reset as soon as we switch the view, from Apps to Timeline or vice versa. This is a real bummer.
 
Instead, we'd love to have the filter sticky and consistent for (ideally) all views (pages) without resetting on a view change. It would be really cool to have the filters be sticky and survive when going from one view to another, maybe even between multiple sessions. 

<img width="586" alt="Screenshot 2022-08-24 at 12 10 23" src="https://user-images.githubusercontent.com/80452889/186396260-164fc7bd-f0ae-4cfb-9e66-eed5ebbba555.png">
<img width="774" alt="Screenshot 2022-08-24 at 12 33 42" src="https://user-images.githubusercontent.com/80452889/186397347-fb3b44e4-7cae-45e0-af67-86944c66a118.png">

I understand that it might get tricky, given the point that Apps and Timeline have a different set of filters. But the fields not available for Apps (`Events Name` and `Priority`) could simply be greyed out (probably reordered, too) and only active for the Timeline.

Thanks for the great product you are delivering!

**Comment by kayahk** [comment]
While thinking about it and using the filters, I figured it would also be great to have another field for the Timeline to filter out the [RESOLVED] events from being listed and only display events that currently don't have the `RESOLVED` status.

**Comment by Noamstrauss** [comment]
We would like this feature as well.

**Comment by arikalon1** [comment]
Thanks for reporting it @kayahk and @Noamstrauss 
We're going to implement the parameters presets in the UI.

For now, as a workaround, you can save the URL of a specific filter selection. The parameters are part of the URL, so it can make it easier to access previous filter selection.

Regarding the RESOLVED status filtering, it's on our roadmap as well

**Comment by Benjamin-volk** [comment]
I agree with @kayahk as well, hopefully, this will be implemented soon :)

**Comment by aantn** [comment]
Hey all, we've added presets to the UI. Does the current implementation work for your needs?

**Comment by pavangudiwada** [comment]
Closing this issue as it is resolved, and we do not have new requests.
