### ISSUE TITLE
regex for alert silencer in web ui inverts expression

### ISSUE THREAD

**Issue by kayahk** [robusta-dev/robusta#496]
**Describe the bug**
When adding a new silence record with a regex match like `.+` the silence created in alertmanager is ending up like this `alertname!~".+"` which does not catch any alert at all.
 
**To Reproduce**
1. Go to 'Silences'
2. Click on '+ New Silence'
3. Enter any value for field `Matcher`, like 'alertname' and add value for `Matches regex`like this: `.+` 
4. check silencer in alertmanager

**Expected behavior**
The expression in alertmanager should look like `matcher_name=~"+."`, but instead contains `matcher_name!
see screenshots with one wrong record from Robusta and one manually created correct record.
<img width="518" alt="Screenshot 2022-08-26 at 11 43 16" src="https://user-images.githubusercontent.com/80452889/186876860-bc759961-8b4e-46e5-87c5-57ee3dc1586e.png">

**Comment by RoiGlinik** [comment]
@kayahk , Did you get a chance to look at the fix?

**Comment by kayahk** [comment]
@RoiGlinik yes, looks good now, thank you very much.
