### ISSUE TITLE
Adding templating to the customise_finding

### ISSUE THREAD

**Issue by adecchi-2inno** [robusta-dev/robusta#510]
**Describe the bug**
Adding templating to the **customise_finding**, at the moment when you use **resource_babysitter** many  fields are lost, and it is not possible to identify what application triggered it.

**To Reproduce**

`

- triggers:
    - on_deployment_update: {}
  actions:
    - resource_babysitter:
        omitted_fields: []
        fields_to_monitor: ["spec.replicas", "image"]
    - customise_finding:
        title: "Deployment Changed: $name on namespace: $namespace"
        description: "Replicas/Application changed"
        severity: "INFO"
        aggregation_key: "Deployment Changed"
  sinks:
    - "xxxx"

`
<img width="639" alt="image" src="https://user-images.githubusercontent.com/75376949/187726848-e2693d27-fc87-47ed-8628-d5f648389b51.png">

**Expected behavior**
Allow us to identify what application triggers the alert with custom details, like $name, $namespace, and others.

**Comment by arikalon1** [comment]
Thanks for reporting it @adecchi-2inno 
We'll fix it shortly
