### ISSUE TITLE
Some alerts or alert types are missing fingerprint

### ISSUE THREAD

**Issue by taivo123** [robusta-dev/robusta#517]
**Describe the bug**
Some alerts or alert types are missing fingerprint.
It is possible, that KUBERNETES_API_SERVER sourced alarms are missing the fingerprint, but PROMETHEUS sourced alarms have it
Some examples with missing fingerprint:
- Crashing pod
- Updates to significant fields
- `robusta playbooks trigger prometheus_alert`

**To Reproduce**
1. generate _Updates to significant fields_ alert (for example with `resource_babysitter` action)
2. observe how the fingerprint field is missing (for example with `print(f"fingerprint ::: {finding.fingerprint} ")`)

**Expected behavior**
Expecting fingerprint to be present for most, if not all alerts

**Comment by aantn** [comment]
I wonder if we should be including the cluster name in the hash too. #525 implies that the cluster name needs to be included in the hash for OpsGenie.
