### ISSUE TITLE
New Sink: PushOver

### ISSUE THREAD

**Issue by Ph3nol** [robusta-dev/robusta#556]

**Comment by arikalon1** [comment]
Thank you for reporting it @Ph3nol 

Can you describe a little the need to get the notifications on PushOver?

Can Telegram sink be useful to you? 
https://docs.robusta.dev/master/catalog/sinks/telegram.html#telegram

We also used the Webhook sink and ntfy.sh to push notifications
https://docs.robusta.dev/master/catalog/sinks/webhook.html#webhook

**Comment by aantn** [comment]
We now support Pushover :)

https://docs.robusta.dev/master/configuration/sinks/pushover.html#pushover

Good luck and please share any feedback.
