### ISSUE TITLE
If possible, can i send the notification on email?

### ISSUE THREAD

**Issue by sachinvasle99** [robusta-dev/robusta#568]
**Is your feature request related to a problem?**
Please describe a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alikhanxgrid** [comment]
@arikalon1 i will try to add it

**Comment by arikalon1** [comment]
Email (smtp) sink was released today as part of 0.10.26
