### ISSUE TITLE
PagerDuty: invalid routing key

### ISSUE THREAD

**Issue by polandj** [robusta-dev/robusta#571]
**Describe the bug**
When trying to use the pagerDuty sink, it complains about an "invalid routing key". 

**To Reproduce**
1. Setup pager duty sink in generated values yaml.
2. Generate issue with a crashing pod.
3. Invalid Routing key error appears in log of robusta-runner pod.
4. Nothing appears in pagerduty

**Expected behavior**
An export to pagerduty.

**Kubernetes**
 - v1.24.4+k3s1

**Additional context**
I added this config in the sinksConfig section:

```
- pagerduty_sink:
    name: main_pagerduty_sink
    api_key: (MYAPIKEY)
```

The actual error in the log:

`2022-10-12 23:04:09.227 ERROR    Error sending message to PagerDuty: 400, Bad Request, Invalid routing key`

**Comment by polandj** [comment]
Totally works as described in video.  Thanks!

**Comment by aantn** [comment]
@polandj glad to hear it! (I'm the guy in the video.)

If you have any other questions, feel free to reach out. We're also available on [Slack](https://bit.ly/robusta-slack).
