### ISSUE TITLE
Runner image not available !

### ISSUE THREAD

**Issue by woot3d** [robusta-dev/robusta#583]
**Describe the bug**
Im deploying robusta from the provided chart but looks like the runner image is not available anymore, i tried even to pull it separately and i got same result .

**To Reproduce**
1. Go to 'helm folder '
2. Click on 'values.yaml'
3. try to download the runner image (us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:0.0.0)
4. See error that the image is not available 

**Expected behavior**
From where i can pull this image, and is it expected to have that issue ?!

**Comment by aantn** [comment]
Hey, can you try downloading the helm chart as follows:

```
helm repo add robusta https://robusta-charts.storage.googleapis.com && helm repo update
helm pull robusta/robusta
```

That should create a file named something like `robusta-0.10.6.tgz`.

The values file in GitHub is modified during our build process, so the image tag has 0.0.0 placeholder. Sorry about the confusion!

Note that we have full installation instructions in the [docs](https://docs.robusta.dev/master/installation.html) which also cover generating API keys, e.g. for Slack.

**Comment by woot3d** [comment]
Hey @aantn 

Thanks for the prompt response, much appreciated i really want to discover more that tool as i believe that its a great addition to k8s world and that could be a game changer for k8s SRE teams .

So i followed your instruction and tried to install it but i had this error ,i double checked the values.yaml and the annotation block is emtpy so not really sure about the installation logic , here is the error that i get 

`Error: template: robusta/templates/runner.yaml:18:20: executing "robusta/templates/runner.yaml" at <.Values.runner.annotations>: nil pointer evaluating interface {}.annotations`

Thanks in advance

**Comment by arikalon1** [comment]
Hi @woot3d 

I assumed you pulled our helm repo locally.
What was the command you ran, that generated that error?

**Comment by woot3d** [comment]
Yea, i tried to install it , here are details :

```
helm -n robusta install rb robusta/ -f values.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ../.kube/config.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: ../.kube/config.yaml
Error: template: robusta/templates/playbooks-config.yaml:9:7: executing "robusta/templates/playbooks-config.yaml" at <include "robusta.configfile" .>: error calling include: template: robusta/templates/_helpers.tpl:6:4: executing "robusta.configfile" at <fail "At least one sink must be defined!">: error calling fail: At least one sink must be defined!
 helm install rb robusta/ -f generate-val.yaml
Error: template: robusta/templates/runner.yaml:18:20: executing "robusta/templates/runner.yaml" at <.Values.runner.annotations>: nil pointer evaluating interface {}.annotations
```

thanks @arikalon1 , Hope that can help, !

**Comment by arikalon1** [comment]
Regarding that values.yaml file, is it the file found in the chart directory?

Did you use the robusta cli `gen-config` command, to create your `generated_values.yaml` file?

Regardless, you can join our community slack channel, we're available there as well.
You can find the join link on: https://home.robusta.dev/slack

**Comment by woot3d** [comment]
Thanks @arikalon1 , but i tried both values , the default one as well as a simple one that have the minimum that i generated with `gen-config`

here is my generated-values file 

```
globalConfig:
  signing_key: xxx-xxxxx-xxxxx-xxxxxx
  account_id: xxx-xxxxx-xxxxx-xxxxxx
sinksConfig: []
clusterName: MyFDQN
disableCloudRouting: true
```

let me know if i'm missing anything here .

Thanks

**Comment by arikalon1** [comment]
Got it.

You should use the `generated_values.yaml` file.

You need to have at least one `sink`, otherwise the result aren't sent anywhere.
I recommend using the Robusta UI sink, or the Slack sink (specify that when running the `gen-config` command)

Once you created the `generated_values.yaml` file, with at least one sink, I would try installing using the helm repo (no need to download a copy of the chart)

```
 helm repo add robusta https://robusta-charts.storage.googleapis.com && helm repo update
 helm install robusta robusta/robusta -f ./generated_values.yaml --set clusterName=<YOUR_CLUSTER_NAME> 
```

Can you try that?

**Comment by RoiGlinik** [comment]
@woot3d Did it work for you ?

**Comment by aantn** [comment]
@pavangudiwada did we fix the relevant docs / add a comment to the chart around this?

Can we close?

**Comment by pavangudiwada** [comment]
Oh, yes. [Here](//github.com/robusta-dev/robusta/pull/643)

**Comment by pavangudiwada** [comment]
@aantn I believe this can be closed.

**Comment by aantn** [comment]
Thanks, closing
