### ISSUE TITLE
Readme links to multiple 404 pages.

### ISSUE THREAD

**Issue by gurpalw** [robusta-dev/robusta#589]
**Describe the bug**
[Kubernetes monitoring - prebuilt Prometheus integration that enriches alerts with extra context and graphs](https://home.robusta.dev/prometheus-based-monitoring/?from=github)
Event-triggered automations for Kubernetes (like Argo Events) with an emphasis on simplicity
Auto-remediations - out of the box fixes for common alerts. Write your own in Python.
[Change tracking - track and audit every change to your Kubernetes cluster](http://home.robusta.dev/ui?from=github)

These links from the README.md are dead.

**Comment by aantn** [comment]
Thank you for reporting! Fixed those two links.

@pavangudiwada will do a more thorough analysis to see if we missed any other links. In the meantime, if you find anything else please let us know!
