### ISSUE TITLE
Add support for authorization header when calling Prometheus

### ISSUE THREAD

**Issue by arikalon1** [robusta-dev/robusta#616]
Some Prometheus installations requires authentication.

For example, when using https://github.com/openshift/oauth-proxy to authenticate requests to Prometheus.

We'd like to provide a Bearer token, that can be sent to Prometheus in an Authorization header

**Comment by bear-redhat** [comment]
The basic requirement would be allowing adding the token to the values file.

There are one additional (nice to have) feature to this:
The token has an expiry date and will be rotated regularly. Thus, it would be great if we can specify a `secret` name in the values file, so we can just rotate the secret without re-applying values.
