### ISSUE TITLE
 No endpoints available for service "robusta-kube-prometheus-st-operator"

### ISSUE THREAD

**Issue by Braineanear** [robusta-dev/robusta#617]
**Describe the bug**
I'm trying to re-install robusta using helm after removing it before but this error appears to me.

Error: INSTALLATION FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://robusta-kube-prometheus-st-operator.robusta.svc:443/admission-prometheusrules/validate?timeout=10s": no endpoints available for service "robusta-kube-prometheus-st-operator"

I searched a lot in the cluster but there is no service for robusta-kube-prometheus-st-operator and i removed everything related to robusta hopping this error disappears but it still returning when installing robusta or even when installing prometheus operator.

**To Reproduce**
i only runs
``
helm install robusta robusta/robusta -f robusta.yaml -n robusta --create-namespace
``

**Screenshots**
![Screenshot 2022-12-02 150815](https://user-images.githubusercontent.com/17293532/205299910-0d801d4e-5b1a-4573-b0ba-56ef6c75f6f6.png)

**Comment by Braineanear** [comment]
solved by deleting robusta-kube-prometheus-st-admission from mutatingwebhookconfigurations and validatingwebhookconfigurations
`kubectl delete mutatingwebhookconfigurations robusta-kube-prometheus-st-admission`
`kubectl delete validatingwebhookconfigurations robusta-kube-prometheus-st-admission`

**Comment by arikalon1** [comment]
Thanks for reporting it @Braineanear
