### ISSUE TITLE
SSH HostKeys are not verified with git commands permitting MITM attacks (GitRepo)

### ISSUE THREAD

**Issue by rudis** [robusta-dev/robusta#619]
Hello,

`src/robusta/integrations/git/git_repo.py` contains the following code:
```python
os.system(f"ssh-keyscan -H github.com bitbucket.org >> {SSH_ROOT_DIR}/known_hosts")
```
While this makes it easy to connect via SSH it also completely bypasses hostkey checks.

This should not be the default! From what I can see it's also not documented.

While testing git_audit_change I also didn't find a way to specify additional hostkeys; in my case to connect to a non-Github git server.

Best,
Simon

**Comment by arikalon1** [comment]
Thanks for reporting it @rudis 

Your description of the problem is accurate.
We will add host keys configuration option, and will change the default behavior

**Comment by llavin** [comment]
Is the host key config option being worked on?

**Comment by arikalon1** [comment]
Hi @llavin 
No one is working on it at the moment

**Comment by RobertSzefler** [comment]
@llavin @rudis https://github.com/robusta-dev/robusta/pull/1313
