### ISSUE TITLE
Ability to advanced filtering any alert

### ISSUE THREAD

**Issue by lictw** [robusta-dev/robusta#687]
Will be great if I will can set some burst time for triggers like annoying events, for example to send in my slack only the one alert every 4 hours, not more, when original K8s event will be spammed every minute. You also can imagine more parameters like regex filter for message or severity level.

**Comment by arikalon1** [comment]
thanks for reporting this @lictw 
Prometheus alerts already fires once every 4 hours

Can you give an example of what other event you'd like to rate limit

**Comment by aantn** [comment]
@lictw we're currently considering new features around this capability, including grouping into Slack threads. Would you be open to jumping on a short call and providing feedback on some ideas?

**Comment by arikalon1** [comment]
hey @lictw 

We have just released [Slack Notifications Grouping](https://docs.robusta.dev/master/configuration/notification-grouping.html)

Does that help with your requirements?

**Comment by lictw** [comment]
@arikalon1 Yep, seems very cool, but we don't use Slack more (and Robusta toio, it's on hold, but we are planning to come back, it's just not up to that yet).
