### ISSUE TITLE
Configurable cluster name label for api.robusta.dev alertmanager webhook

### ISSUE THREAD

**Issue by mario-steinhoff-gcx** [robusta-dev/robusta#697]
**Is your feature request related to a problem?**

I am trying to integrate robusta with our existing monitoring setup.

In this scenario I have a cluster where prometheus-operator and prometheus are deployed via the `kube-prometheus-stack` helm chart, but without alertmanager, grafana, dashboards, recording rules, etc. The prometheus-operator is only used to deploy a prometheus instance and to generate prometheus scrape config from e.g. `ServiceMonitor` CRDs. This cluster-local prometheus instance then remote-writes all metrics to a multi-tenant mimir instance (on a different management cluster and with mimir ruler and mimir alertmanager deployed), and thats where all the rules are stored and evaluated. On this management cluster I also deployed the standalone grafana helm chart connected to mimir and mimir alertmanager. I still wanted the default dashboards and rules from the kube-prometheus-stack helm chart, but those are actually coming from `kubernetes-monitoring/kubernetes-mixin` monitoring mixin, so I took the `kubernetes-mixin` mixin and used a bit of jsonnet magic to deploy the dashboards to grafana and rules to mimir alertmanager. So far, this worked well.

The robusta forwarder is already running and works like a charm but I ran into some problems with alertmanager. I am using the configuration for [Out-of-cluster Prometheus Installations](https://docs.robusta.dev/master/user-guide/alert-manager.html#out-of-cluster-prometheus-installations), where it says:

> Make sure that your alerts contain a label named `cluster_name` which matches the cluster_name defined in Robusta's configuration. This is necessary so that the Robusta cloud knows which cluster to forward events to.

The kubernetes-mixin (e.g. [here](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/eb707bf721dc702baeac2827345e531d6fd207e1/config.libsonnet#L85)) and prometheus (e.g. [here](https://prometheus.io/docs/alerting/latest/configuration/#example)) name their cluster label `cluster`, but the robusta webhook receiver expects a `cluster_name` which cannot be changed.

So right now this blocks me from forwarding alerts into robusta because the cluster correlation won't work.

**Describe the solution you'd like**

I would like to stick with the convention and use the `cluster` label for robusta.

For this I need a way to set a different cluster label in the robusta UI.

**Describe alternatives you've considered**

I could rename our existing label to `cluster_name` it, but

- it looks like there's already a convention around the `cluster` label
- renaming will lead to dashboards not showing data before the rename anymore (or add extra complexity in promql queries that have to account for multiple labels, I'd like to avoid this)
- renaming will lead to high-cardinality issues and increased resource consumption in our ingesters for 12h (I could increase the limits temporarily but I'd like to avoid this additional work)

**Comment by sebv004** [comment]
Same trouble, I cannot rename cluster to cluster_name without breaking dashboards, alertrules, ...
So, I will copy the label cluster to cluster_name in prometheusSpec.externalLabels, quite dirty ...

**Comment by arikalon1** [comment]
hey @sebv004 

I think we should add support for `cluster` label as well
I think we can fix it within couple of days

maybe not worth implementing that ugly workaround

**Comment by sebv004** [comment]
I already did it on our test env.
Would be great to get such feat. before going to prd on our new platform.

**Comment by arikalon1** [comment]
You can now use both `cluster` and `cluster_name` labels
