### ISSUE TITLE
New Sink: Is there any supported sinks for outlook mail?

### ISSUE THREAD

**Issue by nithish407** [robusta-dev/robusta#699]
**Is your feature request related to a problem?**
Please describe a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arikalon1** [comment]
Hi @nithish407 

Please follow issue #363 , it's about email sink
We're going to add it soon

**Comment by arikalon1** [comment]
fixed by #1128
