### ISSUE TITLE
add an assignee option to Jira sink

### ISSUE THREAD

**Issue by iamsreelakshminair** [robusta-dev/robusta#713]
Add the option to define an `assignee` on the Jira sink configuration

**Comment by aantn** [comment]
Hi, which sink does this relate to?

**Comment by ivankovnatsky** [comment]
This should be already implemented, forgive me if I missed something. Reference: https://docs.robusta.dev/master/configuration/sinks/jira.html.

**Comment by arikalon1** [comment]
Hey @ivankovnatsky 

you're right. `assignee` is already implemented
Closing it
