### ISSUE TITLE
Why does RESOLVED is not green light ?)

### ISSUE THREAD

**Issue by emoxam** [robusta-dev/robusta#733]
![image](https://user-images.githubusercontent.com/3593601/219371656-bf4ce845-9bad-408c-ae5b-1cc8507d46d3.png)
Why does RESOLVED is not green light ?)

**Comment by aantn** [comment]
Hey, right now the color represents the priority of the original alert. So if a HIGH alert becomes RESOLVED then we still keep the color red. I'm forwarding this to the team though!

**Comment by aantn** [comment]
Looks like we're already doing the right thing on Slack, but the colors are wrong on Telegram.

**Comment by emoxam** [comment]
> Looks like we're already doing the right thing on Slack, but the colors are wrong on Telegram.

yep, thanks)

**Comment by bhavyastar** [comment]
Hey @aantn I would like to work on this issue!

**Comment by aantn** [comment]
Go for it!

I'd recommend getting started by reading the sink guide: https://docs.robusta.dev/master/developer-guide/platform/sinks-guide.html

Then you'll want to edit files here: https://github.com/robusta-dev/robusta/tree/master/src/robusta/core/sinks/telegram

Possibly using Slack as reference (this is already implemented for Slack): https://github.com/robusta-dev/robusta/tree/master/src/robusta/core/sinks/slack

**Comment by ganeshrvel** [comment]
Should get fixed in https://github.com/robusta-dev/robusta/pull/775/files
