### ISSUE TITLE
Possibility to disable the `Investigate` button for the slack sink

### ISSUE THREAD

**Issue by otherguy** [robusta-dev/robusta#734]
I would like a flag to disable the `Investigate` button on the slack sink. 

We send alerts via 2 slack sinks. One goes to our infra team, that has access to the Robusta UI, and we want to keep the button there. Another set of alerts goes to a channel that is monitored by all engineers, and we don't want to introduce a new tool to them, so we want to disable the `Investigate` button on that second slack sink.

**Comment by arikalon1** [comment]
will be included in release 0.14.2
