### ISSUE TITLE
Integration with service Now

### ISSUE THREAD

**Issue by seyal84** [robusta-dev/robusta#751]
**Is your feature request related to a problem?**
Please describe a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
No
**Describe the solution you'd like**

I would prefer for observability stack to generate ServiceNow tickets / incidents based on the alerts / notifications.

Should have the ability to set the alert type I.e INFO/ERROR/warning/Servere etc. 

**Describe alternatives you've considered**

Simple notification on the slack 

**Additional context**

**Comment by Sheeproid** [comment]
Hey @seyal84 , I'd like to have a chat about how you're planning to use a ServiceNow integration.
Can you please send an email to tomer@robusta.dev or message me in the [Robusta Slack Community](https://join.slack.com/t/robustacommunity/shared_invite/zt-1h4wjwcki-VpEMAuwxlNb~ko9x2F~1tw)?
