### ISSUE TITLE
Error in runner logs related to playbook reloading

### ISSUE THREAD

**Issue by metheu** [robusta-dev/robusta#773]
hi! Not sure this is a bug but it might be an issue. There are error logs in runner related to playbook reloading and it might be effecting its execution. To be honest, I was trying to configure alertmanger to forward alerts to robusta and it seems like this error might be hampering it. 

`RUNNER_VERSION : 0.10.13`

Here are the logs:
`
2023-03-08 07:58:16.604 INFO     loading config /etc/robusta/config/active_playbooks.yaml
2023-03-08 07:58:16.646 ERROR    unknown error reloading playbooks. will try again when they next change
Traceback (most recent call last):
  File "/app/src/robusta/runner/config_loader.py", line 161, in __reload_playbook_packages
    runner_config = self.__load_runner_config(self.config_file_path)
  File "/app/src/robusta/runner/config_loader.py", line 277, in __load_runner_config
    return RunnerConfig(**yaml_content)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 28 validation errors for RunnerConfig
sinks_config -> 0 -> robusta_sink
  field required (type=value_error.missing)
sinks_config -> 0 -> slack_sink
  none is not an allowed value (type=type_error.none.not_allowed)
sinks_config -> 0 -> jira_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> robusta_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> slack_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> datadog_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> kafka_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> ms_teams_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> opsgenie_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> telegram_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> webhook_sink
  none is not an allowed value (type=type_error.none.not_allowed)
sinks_config -> 1 -> victorops_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> pagerduty_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> discord_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> mattermost_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> webex_sink
  field required (type=value_error.missing)
sinks_config -> 1 -> jira_sink
  field required (type=value_error.missing)
2023-03-08 07:58:16.647 INFO     Telemetry set to include error info, Thank you for helping us improve Robusta.
2023-03-08 07:58:16.711 ERROR    Sentry error: 'Registry' object has no attribute 'global_config'
Traceback (most recent call last):
  File "/app/src/robusta/runner/telemetry_service.py", line 34, in __init__
    global_config = self.registry.get_global_config()`

**Comment by RoiGlinik** [comment]
For future reference , this  `sinks_config -> 0 -> slack_sink none is not an allowed value (type=type_error.none.not_allowed) `  usually happens when theres in indentation error in the sinkConfig ( inside you config file) 
and the sink is missing its params.

example:

```
sinksConfig:
- slack_sink:
  name: main_slack_sink
  slack_channel: channel
  api_key: xobo-key
```
  
 The fix should be 
 
 ```
sinksConfig:
- slack_sink:
    name: main_slack_sink
    slack_channel: channel
    api_key: xoxb-key
```
