### ISSUE TITLE
Add pull secrets for images and external registry image ( airgap) - promethus - robusta

### ISSUE THREAD

**Issue by villadalmine** [robusta-dev/robusta#783]
**Is your feature request related to a problem?**
Please describe a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Im using jfrog in our infra and i am not able to change image name in values.yaml and also secrets pull for image.

It is not possible to use also robusta prometheus stack because in the helm chart it is in a tgz file pointing to prometheus-stack

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arikalon1** [comment]
Hi @villadalmine 
Thanks for reporting it

Just to make sure I understand your requirement, you would like to change the `prometheus` image, and to provide `imagePullSecrets` for pulling it.

is that correct?

**Comment by villadalmine** [comment]
Hi,

I need this :

something like this for robusta helm chart and also for prometheus
imagePullSecrets: []
# - name: secretName

and also for both:

controller:
  name: controller
  image:
    repository: k8s.gcr.io/ingress-nginx/controller
    tag: "v0.41.2"
    digest: sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de\

I used ingress-nginx as example, but the goal is related to have the option to use my own image registry and add also image pull secret, because im using jfrog the image were download in jfrog using cache and then i collect it in my infra throw jfrog, it is kind of AIRGAP method.

Regards

**Comment by villadalmine** [comment]
Hi, any update @arikalon1 , thanks

**Comment by arikalon1** [comment]
Hi @villadalmine 

We added few options to provide image pull secrets:
[runner service account](https://github.com/robusta-dev/robusta/blob/59db41666035aa323f34379d3ee2597545b42fdd/helm/robusta/values.yaml#L510) : This will be used for the runner image, and other images used by the runner. (the runner can run popeye best practices scan, or krr resource recommendation scan)
[runner](https://github.com/robusta-dev/robusta/blob/59db41666035aa323f34379d3ee2597545b42fdd/helm/robusta/values.yaml#L535) : Better to use the service account
[forwarder](https://github.com/robusta-dev/robusta/blob/59db41666035aa323f34379d3ee2597545b42fdd/helm/robusta/values.yaml#L460)

kube-prometheus-stack also supports it:
you just need to add to the `generated_values.yaml`:
```
kube-prometheus-stack:
  global: 
    imagePullSecrets: 
    ....      
```

Closing the issue for now.
If you need additional assistance, feel free to reopen it
