### ISSUE TITLE
Allow Robusta to use queries in prometheus url - Multi Cluster Victoriametrics 

### ISSUE THREAD

**Issue by sumeet-zuora** [robusta-dev/robusta#824]
**Is your feature request related to a problem?**
Would like to use Single VM instance which have a label for differentiating multiple clusters ..let us say using `cluster`

**Describe the solution you'd like**

We can give prometheus url like https://vmselect.eks.dev/select/0/prometheus?extra_label=cluster=3-prod

**Comment by arikalon1** [comment]
Hi @sumeet-zuora 

We added the ability to add custom labels to VM (or other centralized Prometheus like metrics storage)
It's documented [here](https://docs.robusta.dev/master/configuration/alertmanager-integration/victoria-metrics.html#configure-pull-integration)

Closing the issue
