### ISSUE TITLE
Support for Azure managed Prometheus

### ISSUE THREAD

**Issue by EppO** [robusta-dev/robusta#848]
**Is your feature request related to a problem?**
I use Azure Managed Prometheus that doesn't allow to change alertmanager config

**Describe the solution you'd like**
It would be super neat to be able to call robusta webhook from Azure Monitor (as Action Group Id or something)

**Describe alternatives you've considered**
Installing Prometheus in the cluster but it's redundant. An Azure function that translates the azure alert into a robusta webhook is another alternative 

**Additional context**
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/prometheus-rule-groups#create-prometheus-rules

**Comment by aantn** [comment]
It's being worked on right now 🙂

Will have updates in the coming week or so.
