### ISSUE TITLE
dynamic slack sink configuration for channel

### ISSUE THREAD

**Issue by mitch-mckenzie** [robusta-dev/robusta#875]
**Is your feature request related to a problem?**
We would like to be able to configure the slack sink to match a label on a Finding so the slack sink can infer what channel to send a finding to. 

**Describe the solution you'd like**

something like:

- slack_sink:
    name: slack-sink
    slack_channel: alerts
    api_key: xyz-abc
    slack_channel_label_re_match: (team_slack_channel|slack_channel)

**Describe alternatives you've considered**
specifying a sink for every teams slack channel.  creating a custom sink that can make the api call to slack with a dynamic channel.

**Additional context**
none.

**Comment by RoiGlinik** [comment]
@mitch-mckenzie  this is now supported , for more info
https://docs.robusta.dev/master/configuration/sinks/slack.html#dynamic-slack-channels
