### ISSUE TITLE
Not able to pull runner and forwarder images from private registry if auth is required

### ISSUE THREAD

**Issue by philslab-ninja** [robusta-dev/robusta#901]
**Is your feature request related to a problem?**
Using Helm it is not possible to pull the images from a private registry requiring authentication

**Describe the solution you'd like**
Add imagePullSecrets to the helm template for runner and kubewatch:
Example:
```      containers:
      - name: runner
        image: {{ .Values.runner.image }}
        imagePullPolicy: {{ .Values.runner.imagePullPolicy }}
        imagePullSecrets: {{ .Values.runner.imagePullSecrets }}
```

And make it configurable using the values.yaml:

```
runner:
  imagePullSecrets: []
```

**Describe alternatives you've considered**
Patching the service accounts created. Not a nice workaround:
```
kubectl patch -n "monitoring" serviceaccount robusta-runner-service-account -p '{"imagePullSecrets": [{"name": "my-pull-secret"}]}'
kubectl patch -n "monitoring" serviceaccount robusta-forwarder-service-account -p '{"imagePullSecrets": [{"name": "my-pull-secret"}]}'
```

**Comment by aantn** [comment]
Hi @philslab-ninja,
Would you be interested in opening a PR to fix this?

**Comment by RoiGlinik** [comment]
@philslab-ninja , imagePullSecrets: [] , is now supported
