### ISSUE TITLE
Robusta cli cannot reach runner

### ISSUE THREAD

**Issue by oscarmparedes** [robusta-dev/robusta#919]
**Describe the bug**
I have deployed robusta using helm chart via flux2 helmrelease. Generated values initially with robusta cli, added custom playbooks to values, then generated a helmrelease file deployed. All working good, however I cannot trigger playbooks manually using the cli. KUBECONFIG variable is set to the cluster where I deployed robusta, and Im in the same dir I created the `generated_values.yaml` file. I can't really use the cli to interact with robusta, Im seeing the following errors: 

```
Triggering action...
======================================================================
running cmd: curl -X POST http://localhost:5000/api/trigger -H 'Content-Type: application/json' -d '{"action_name": "popeye_scan", "action_params": {}}'
error: pod, type/name or --filename must be specified
error: Cannot trigger playbook - usually this means Robusta just started. Will try again
error: pod, type/name or --filename must be specified
error: Cannot trigger playbook - usually this means Robusta just started. Will try again
======================================================================
Fetching logs...
======================================================================
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples
======================================================================
Cannot fetch logs. robusta-runner not found
======================================================================
======================================================================
Done!
```

**To Reproduce**
1. generate values using robusta cli and deploy to cluster in a custom namespace (robusta)
2. set KUBECONFIG env var to point to the kubernetes cluster were you deployed robusta.
3. run `export DOCKER_DEFAULT_PLATFORM=linux/amd64` to allow docker cli running in m1 Mac to use amd64 images.
4. run the robusta cli docker version to list playbooks: `./robusta playbooks list`

**Expected behavior**
Interact with the features robusta cli offers.

**Screenshots**

**Desktop (please complete the following information):**
MacOS Ventura 13.4 m1.

**Additional context**
As I said, probably Im just doing something wrong but just not seeing the same issue happening to anyone here in issues nor in documentation, so Im assuming its pretty straight forward and Im just overlooking something. Thanks!

**Comment by aantn** [comment]
Does it work with `./robusta playbooks list --namespace=robusta`?

**Comment by oscarmparedes** [comment]
it does! thanks!, can't believe I missed this.

**Comment by aantn** [comment]
Cool, making the error message more clear in #921 and closing this.

Thanks for reporting :)
