### ISSUE TITLE
Added Some Styling at Automation engine

### ISSUE THREAD

**Issue by kumarankit999** [robusta-dev/robusta#931]
**Describe the bug**
If we see below in the Automation engine image, The both two lines have been clashed.

**Expected behavior**
There should be some gap between these two lines. So, We Can add some Margin and Padding there to remove the clash

**Screenshots**

![image](https://github.com/robusta-dev/robusta/assets/111564362/fb968d23-dc5b-4ea8-b417-7d42bba20e9c)

It should looks like this 
![image](https://github.com/robusta-dev/robusta/assets/111564362/ad1852b0-9b75-4f6d-8d47-00e960c332be)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aantn** [comment]
Closing, if this is still relevant feel free to re-open.
