### ISSUE TITLE
Support assigning K8s Name to custom resources

### ISSUE THREAD

**Issue by djfinnoy** [robusta-dev/robusta#945]
**Is your feature request related to a problem?**
In the UI I'm seeing `K8s Name: Unresolved` for an Alert relating to an ArgoCD `Application` CRD that I defined.
On Slack the following information was shared on how `K8s Name` is defined:

```
    Deployment: deployment, namespace
    DaemonSet: daemonset, namespace
    StatefulSet: statefulset, namespace
    Job: job_name, namespace
    Pod: pod, namespace
    HorizontalPodAutoscaler: horizontalpodautoscaler, namespace
    Node: node
```

Since my alert doesn't have any of these labels, the K8s Name is unresolved.

**Describe the solution you'd like**

That information should probably be added to the docs.

Furthermore, I would like a solution where the user can manually assign the alert a robusta K8s name, perhaps through a special alert label.

**Comment by aantn** [comment]
Fixed with https://github.com/robusta-dev/robusta/pull/1170

@djfinnoy you can now customize the labels that are used for mapping. Does that help with the manual assignment in your case?

**Comment by djfinnoy** [comment]
<img src="https://media4.giphy.com/media/AeWoyE3ZT90YM/giphy.gif"/>
